In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
pd.read_csv("data-01-test-score.csv")

    73  80   75  152
0   93  88   93  185
1   89  91   90  180
2   96  98  100  196
3   73  66   70  142
4   53  46   55  101
5   69  74   77  149
6   47  56   60  115
7   87  79   90  175
8   79  70   88  164
9   69  70   73  141
10  70  65   74  141
11  93  95   91  184
12  79  80   73  152
13  70  73   78  148
14  93  89   96  192
15  78  75   68  147
16  81  90   93  183
17  88  92   86  177
18  78  83   77  159
19  82  86   90  177
20  86  82   89  175
21  78  83   85  175
22  76  83   71  149
23  96  93   95  192

In [3]:
import scikit-image

SyntaxError: invalid syntax (<ipython-input-3-7f732ddeb172>, line 1)

In [4]:
from skimage import data

In [5]:
import os

In [6]:
import shutil

In [7]:
import gzip